import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { WatchlistWrapper } from "@/context/WatchlistContext";
import { CartWrapper } from "@/context/CartContext";
import Header from "@/ui-core/components/molecules/Header";
import { Drawer } from "@/components/ui/drawer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PUBLISHABLE_KEY: string | undefined =
  process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

if (!PUBLISHABLE_KEY) {
  throw new Error("Missing Publishable Key");
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider publishableKey={'pk_test_bWF4aW11bS10YXJwb24tMC5jbGVyay5hY2NvdW50cy5kZXYk'}>
          <Drawer>
            <CartWrapper>
              <WatchlistWrapper>
                <TanstackProvider>
                  <Header />
                  {children}
                </TanstackProvider>
              </WatchlistWrapper>
            </CartWrapper>
          </Drawer>
        </ClerkProvider>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
